policy 2 not finished
Signed-off-by: laurentsimon <laurentsimon@google.com>

diff --git a/.github/workflows/deploy_policy.yml b/.github/workflows/deploy_policy.yml
--- a/.github/workflows/deploy_policy.yml
+++ b/.github/workflows/deploy_policy.yml
@@ -30,17 +30,11 @@ on:
         description: "The labels the k8 resource should match against."
         required: false
         type: string
-      continue-on-error:
-        description: "Prevents a workflow run from failing when a job fails. Set to 'true' to allow a workflow run to pass when a job fails."
-        required: false
-        type: boolean
-        default: false
     outputs:
       attestation-name:
         description: "The artifact name of the signed deloy attestation. (A file with the intoto.jsonl extension)."
         value: ${{ jobs.validate.outputs.attestation-name }}
-      # Note: we use this output because there is no built-in `outcome` and `result` is always `success`
-      # if `continue-on-error` is set to `true`.
+      # TODO: Support PASS, FAIL, INTERNAL_ERROR and AUDIT.
       outcome:
         description: >
           The outcome status of the run ('success' or 'failure').
@@ -169,8 +163,7 @@ jobs:
         id: final
         env:
           SUCCESS: ${{ needs.detect-env.outputs.outcome != 'failure' && needs.generator.outputs.outcome != 'failure' }}
-          CONTINUE: ${{ inputs.continue-on-error }}
         run: |
           set -euo pipefail
           echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> "$GITHUB_OUTPUT"
-          [ "$CONTINUE" == "true" ] || [ "$SUCCESS" == "true" ] || exit 27
+          [ "$SUCCESS" == "true" ] || exit 27
